---
sudo: required
dist: trusty

branches:
  only:
    - master

before_install:
	- openssl aes-256-cbc -K $encrypted_4b87603edc0b_key -iv $encrypted_4b87603edc0b_iv
		-in ./infrastructure/ansible/inventories/staging/hosts.enc -out ./infrastructure/ansible/inventories/staging/hosts -d
	- openssl aes-256-cbc -K $encrypted_4b87603edc0b_key -iv $encrypted_4b87603edc0b_iv
		-in .deploy_key.enc -out ./.deploy_key -d
	- ssh-add ./.deploy-key
  - sudo apt-get update -qq
  - sudo apt-get install python3 -y
  - sudo apt-get install curl -y
  - sudo apt-get install jq -y


install:
  - pip install ansible
  - pip install -r infrastructure/ansible/requirements.txt

script: ./deploy.sh
