sudo: required
dist: xenial
branches:
  only:
  - master

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "curl"
      - "jq"

before_install:
  - openssl aes-256-cbc -K $encrypted_4b87603edc0b_key -iv $encrypted_4b87603edc0b_iv
    -in secrets.tar.enc -out ./secrets.tar -d
  - tar xvf secrets.tar
  - mv staging_hosts infrastructure/ansible/inventories/staging/hosts
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.deploy_key
  - ssh-add ./.deploy_key

install:
  - pip3 install ansible
  - pip3 install -r infrastructure/ansible/requirements.txt

script: "./deploy.sh"
