sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_4b87603edc0b_key -iv $encrypted_4b87603edc0b_iv
    -in secrets.tar.enc -out ./secrets.tar -d
  - tar xvf secrets.tar
  - mv staging_hosts infrastructure/ansible/inventories/staging/hosts
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.deploy_key
  - ssh-add ./.deploy_key
  - sudo apt-get update -qq
  - sudo apt-get install curl -y
  - sudo apt-get install jq -y
  - sudo apt-get install python3 -y
install:
  - pip3 install ansible
  - pip3 install -r infrastructure/ansible/requirements.txt
script: "./deploy.sh"
